# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98887a9a127f3219b649194ad82ebffafc7a93d7deb39f942042077e2d8bb09f469846b44ec3568b55204b133785251dd2c01d74e5344e6aa9d7e6a1947498c8

test:
  secret_key_base: cf566d1b5c0eb47a3a5755177096f12e0260e0f599fd52a521053f9e92245bf8c350464fb579d23dc956482bb38ac0f85643fbed17786f00613a4056157785f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
